### ISSUE TITLE
What license is used for this plugin?

### ISSUE THREAD

**Issue by frost-nzcr4** [alphallc/redmine_xmpp_notifications#11]
Is it free for changes and distribution?

**Comment by frost-nzcr4** [comment]
There are services that could help to choose a license http://choosealicense.com/, http://spdx.org/licenses/, and http://opensource.org/licenses.

**Comment by msva** [comment]
@pmisters @mattiarossi

Don't you have any objections to my decision to make plugin Double licensed on CC0/PD && MIT?

**Comment by pmisters** [comment]
I don't have any objections.

**Comment by cmrd-senya** [comment]
Why have it licensed as `CC0/PD` at all? There are [some objections](https://softwareengineering.stackexchange.com/questions/76148/what-is-the-difference-between-releasing-code-under-the-bsd-license-and-releasin) against it. I would change it to just MIT.

**Comment by msva** [comment]
@cmrd-senya Take a read of LICENSE, please. I mentioned there request to not steal authorship, but we do understand that releasing software under PD have the risk that someone will try to do that.

Although, objection about the "warranty" is interesting one and I guess it will be fun to watch the court trial where somebody will prove that this plugin, say, ruined something.

Anyway, I'd okay with revoking PD (only because of this issue with warranty), if another commiters will

**Comment by cmrd-senya** [comment]
> Anyway, I'd okay with revoking PD (only because of this issue with warranty), if another commiters will

That is nothing that requires their explicit permission because they agreed with PD and MIT which both allow to relicense the software. So they already agreed that their software could be relicensed at any license. So that's the question for the repository owners, not for the commiters.

**Comment by msva** [comment]
Fixed with #14
